- name: Istall Wordpress For Debian
  import_tasks: debian.yaml
  when: ansible_facts['os_family'] == "Debian"

- name: Istall Wordpress For RedHat
  import_tasks: redhat.yaml
  when: ansible_facts['os_family'] == "RedHat"
