- name: Download wordpress
  get_url:
    url: "{{ wp['url'] }}"
    checksum: "{{ wp['sha1'] }}"
    dest: "{{ wp['source'] }}"
  async: 300
  poll: 0
  register: wp_source_result

- name: Install Httpd Package
  yum:
    name: httpd, php, php-mysql, php-gd, php-mbstring
    state: present

- name: Check Httpd Service
  service:
    name: https
    state: started
    enabled: yes

- name: Check on an async Download Wordpress Source
  async_status:
    jid: "{{ wp_source_result.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 100
  delay: 5

- name: Unarchive Wordpress Source
  unarchive:
    src: "{{ wp['source'] }}"
    dest: /var/www/html/
    remote_src: true

- name: Copy and Setting wp config php DB configuration
  template:
    src: wp-config.php.j2
    dest: "{{ wp['config'] }}"

- name: Change Service Port
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
    force: yes
  notify:
    - Httpd Service Restart For RedHat
